
[train]
image_path = "data/kodak-dataset/kodim05.png"
learning_rate = 0.001
num_epochs = 10
patience = 600
scheduler_step_size = 100
scheduler_gamma = 0.9
target_loss = 0.001

#loss_type = "SSIMLoss"
#loss_type = "EdgeLoss"
loss_type = "MSELoss"


[save]
net_save_path = "res/net"
net_name = "new_net.pth"
base_output_path = "res"
image_save_path = "res/img"

[misc]
log_save_path = "logs"


[net]
num_frequencies = 10
#upsample = false

#[[net.layers]]
#type = "LearnableEmbedding"
#out_features = 64

[[net.layers]]
type = "Linear"
out_features = 32
[[net.layers]]
type = "ReLU"
out_features = 32

[[net.layers]]
type = "Linear"
out_features = 32
[[net.layers]]
type = "ReLU"
out_features = 32

[[net.layers]]
type = "Linear"
out_features = 32
[[net.layers]]
type = "ReLU"
out_features = 32

[[net.layers]]
type = "Linear"
out_features = 32
[[net.layers]]
type = "ReLU"
out_features = 32

[[net.layers]]
type = "Linear"
out_features = 3

