
[train]
image_path = "data/processed/1.png"
learning_rate = 0.001
num_epochs = 10000
patience = 600
scheduler_step_size = 1000
scheduler_gamma = 0.9
target_loss = 0.001
loss_type = "SSIMLoss"

[save]
model_save_path = "res/model"
model_name = "new_model.pth"
base_output_path = "res"
image_save_path = "res/img"

[misc]
log_save_path = "logs"

[model]
num_frequencies = 10


[[model.layers]]
type = "Linear"
out_features = 256
[[model.layers]]
type = "ReLU"
out_features = 256

[[model.layers]]
type = "Linear"
out_features = 256
[[model.layers]]
type = "ReLU"
out_features = 256

[[model.layers]]
type = "Linear"
out_features = 256
[[model.layers]]
type = "ReLU"
out_features = 256

[[model.layers]]
type = "Linear"
out_features = 256
[[model.layers]]
type = "ReLU"
out_features = 256

[[model.layers]]
type = "Linear"
out_features = 3

