mode = "RGB"
[train]
image_path = "data/kodak-dataset/kodim05.png"
learning_rate = 0.001
num_steps = 10000
num_epochs = 1
patience = 600
scheduler_step_size = 1000
scheduler_gamma = 0.6
target_loss = 0.0005

#loss_type = "SSIMLoss"
#loss_type = "EdgeLoss"
loss_type = "MSELoss"

[save]
net_save_path = "res"
net_name = "best_model"
base_output_path = "res"
image_save_path = "res"

[misc]
log_save_path = "mlruns"


[net]
#num_frequencies = 10
#upsample = false
#degree = 5
#ffm_out_features = 256
#[[net.layers]]
#type = "LearnableEmbedding"
#out_features = 8
#[[net.layers]]
#type = "FourierFeatureMapping"
#out_features = 256
[[net.layers]]
type = "SineLayer"
out_features = 256
is_first = true
[[net.layers]]
type = "SineLayer"
out_features = 256
[[net.layers]]
type = "SineLayer"
out_features = 256
[[net.layers]]
type = "SineLayer"
out_features = 256
[[net.layers]]
type = "Linear"
out_features = 3
need_manual_init = true
