experiment_name = "LSIREN"

[train]
image_path = "data/kodak-dataset/kodim05.png"

num_steps = 10000
num_epochs = 1

learning_rate = 0.0001
scheduler_step_size = 1000
scheduler_gamma = 0.8

loss_type = "MSELoss"
target_loss = 0.00001
patience = 600

[save]
net_save_path = "res"
net_name = "LSIREN"
base_output_path = "res"
image_save_path = "res"

[misc]
log_save_path = "mlruns"


[net]
#num_frequencies = 10
#upsample = false
#degree = 5
#ffm_out_features = 256
#[[net.layers]]
#type = "LearnableEmbedding"
#out_features = 8
#[[net.layers]]
#type = "FourierFeatureMapping"
#out_features = 256
[[net.layers]]
type = "SineLayer"
out_features = 256
is_first = true
[[net.layers]]
type = "SineLayer"
out_features = 256
[[net.layers]]
type = "SineLayer"
out_features = 256
[[net.layers]]
type = "SineLayer"
out_features = 256
[[net.layers]]
type = "Linear"
out_features = 3
need_manual_init = true
