
[train]
image_path = "tests/edges_output.jpg"
learning_rate = 0.001
num_steps = 1000
num_epochs = 1
patience = 600
scheduler_step_size = 100
scheduler_gamma = 0.9
target_loss = 0.001

#loss_type = "SSIMLoss"
#loss_type = "EdgeLoss"
loss_type = "MSELoss"


[save]
net_save_path = "res"
net_name = "best_model"
base_output_path = "res"
image_save_path = "res"

[misc]
log_save_path = "mlruns"


[net]
num_frequencies = 10
#upsample = false

#[[net.layers]]
#type = "LearnableEmbedding"
#out_features = 8

[[net.layers]]
type = "Linear"
out_features = 128
[[net.layers]]
type = "ReLU"
out_features = 128

[[net.layers]]
type = "Linear"
out_features = 128
[[net.layers]]
type = "ReLU"
out_features = 128

[[net.layers]]
type = "Linear"
out_features = 128
[[net.layers]]
type = "ReLU"
out_features = 128

[[net.layers]]
type = "Linear"
out_features = 128
[[net.layers]]
type = "ReLU"
out_features = 128

[[net.layers]]
type = "Linear"
out_features = 3

