project_root_path = "/home/work/workspace/liu_iot2024_b/projects/MyINR"

[train]
image_path = "data/processed/1.png"
learning_rate = 0.001
num_epochs = 10000
patience = 600
scheduler_step_size = 1000
scheduler_gamma = 0.8
target_loss = 0.001
loss_type = "FullCombinedLoss"

[save]
model_save_path = "res/model/inr_model.pth"
base_output_path = "res"
image_save_path = "img"

[misc]
log_save_path = "logs"

[model]
#in_features = 2  # 通常情况下，输入为 2D 坐标 (x, y)


[[model.layers]]
type = "Linear"
out_features = 32
[[model.layers]]
type = "ReLU"
out_features = 32

[[model.layers]]
type = "Linear"
out_features = 32
[[model.layers]]
type = "ReLU"
out_features = 32

[[model.layers]]
type = "Linear"
out_features = 32
[[model.layers]]
type = "ReLU"
out_features = 32

[[model.layers]]
type = "Linear"
out_features = 32
[[model.layers]]
type = "ReLU"
out_features = 32

[[model.layers]]
type = "Linear"
out_features = 3

