experiment_name = "PE_MLP_Block"

[train]
image_path = "data/kodak-dataset/kodim19.png"

num_steps = 12000
num_epochs = 1

learning_rate = 0.005
scheduler_step_size = 1000
scheduler_gamma = 0.8

loss_type = "MSELoss"
target_loss = 0.00005
patience = 600

[save]
net_save_path = "res"
net_name = "PE_MLP_Block"
base_output_path = "res"
image_save_path = "res"

[misc]
log_save_path = "mlruns"


[net]
use_block_model = true
num_blocks = 4
num_frequencies = 10 # 位置编码的频率数量

[[net.layers]]
type = "Linear"
out_features = 256
use_relu = true
[[net.layers]]
type = "Linear"
out_features = 256
use_relu = true
[[net.layers]]
type = "Linear"
out_features = 256
use_relu = true
[[net.layers]]
type = "Linear"
out_features = 3
