experiment_name = "SIREN_Block_2d"

[train]
image_path = "data/kodak-dataset/kodim03.png"

num_steps = 3000
num_epochs = 1

learning_rate = 0.0005
learning_rate_final_ratio = 0.01
scheduler_step_size =100
scheduler_gamma = 0.99

loss_type = "MSELoss"
target_loss = 0.00005
patience = 600

[save]
net_save_path = "res"
net_name = "SIREN_Block_2d"
base_output_path = "res"
image_save_path = "res"

[misc]
log_save_path = "mlruns"


[net]
use_block_model = false
num_blocks = 9
h_blocks = 3
w_blocks = 3

[[net.layers]]
type = "SineLayer"
out_features = 32
is_first = true
enable_learnable_omega = false
[[net.layers]]
type = "SineLayer"
out_features = 32
enable_learnable_omega = false
[[net.layers]]
type = "SineLayer"
out_features = 32
enable_learnable_omega = false
[[net.layers]]
type = "SineLayer"
out_features = 32
enable_learnable_omega = false
[[net.layers]]
type = "Linear"
out_features = 3
need_manual_init = true