experiment_name = "SIREN"

[train]
image_path = "data/kodak-dataset/kodim05.png"

num_steps = 15000
num_epochs = 1

learning_rate = 0.0005
learning_rate_final_ratio = 0.01
scheduler_step_size =100
scheduler_gamma = 0.99

loss_type = "MSELoss"
target_loss = 0.00005
patience = 600

[save]
net_save_path = "res"
net_name = "SIREN"
base_output_path = "res"
image_save_path = "res"

[misc]
log_save_path = "mlruns"


# enable_learnable_omega = false SineLayer is the same as the original SIREN
[net]
use_block_model = false
[[net.layers]]
type = "SineLayer"
out_features = 256
is_first = true
enable_learnable_omega = false
[[net.layers]]
type = "SineLayer"
out_features = 256
enable_learnable_omega = true
[[net.layers]]
type = "SineLayer"
out_features = 256
enable_learnable_omega = true
[[net.layers]]
type = "SineLayer"
out_features = 256
enable_learnable_omega = true
[[net.layers]]
type = "Linear"
out_features = 3
need_manual_init = true