experiment_name = "Gauss"

[train]
image_path = "data/kodak-dataset/kodim19.png"

num_steps = 15000
num_epochs = 1

learning_rate = 0.003
learning_rate_final_ratio = 0.06
scheduler_step_size = 1000
scheduler_gamma = 0.8

loss_type = "MSELoss"
target_loss = 0.00005
patience = 600

[save]
net_save_path = "res"
net_name = "Gauss"
base_output_path = "res"
image_save_path = "res"

[misc]
log_save_path = "mlruns"


[net]
[[net.layers]]
type = "GaussLayer"
out_features = 256
[[net.layers]]
type = "GaussLayer"
out_features = 256
[[net.layers]]
type = "GaussLayer"
out_features = 256
[[net.layers]]
type = "GaussLayer"
out_features = 256
[[net.layers]]
type = "Linear"
out_features = 3
