experiment_name = "LearnableEmbedding"

[train]
image_path = "data/kodak-dataset/kodim19.png"

num_steps = 15000
num_epochs = 1

learning_rate = 0.00005
scheduler_step_size =100
scheduler_gamma = 0.98

loss_type = "MSELoss"
target_loss = 0.001
patience = 600

[save]
net_save_path = "res"
net_name = "LearnableEmbedding"
base_output_path = "res"
image_save_path = "res"

[misc]
log_save_path = "mlruns"


[net]
num_frequencies = 16
#[[net.layers]]
#type = "LearnableEmbedding"
#out_features = 256
[[net.layers]]
type = "Linear"
out_features = 256
use_relu = true
[[net.layers]]
type = "Linear"
out_features = 256
use_relu = true
[[net.layers]]
type = "Linear"
out_features = 256
use_relu = true
[[net.layers]]
type = "Linear"
out_features = 256
use_relu = true

[[net.layers]]
type = "Linear"
out_features = 3
