experiment_name = "LSIREN"

[train]
image_path = "data/kodak-dataset/kodim05.png"

num_steps = 12000
num_epochs = 1

learning_rate = 0.0001
scheduler_step_size =100
scheduler_gamma = 0.98

loss_type = "MSELoss"
target_loss = 0.00005
patience = 600

[save]
net_save_path = "res"
net_name = "LSIREN"
base_output_path = "res"
image_save_path = "res"

[misc]
log_save_path = "mlruns"


# enable_learnable_omega = true -> SIREN with learnable omegas
# torch.sin(omega_0 * x) -> torch.sin(omegas.mul(x))  omegas: torch.nn.Parameter
[net]
[[net.layers]]
type = "SineLayer"
out_features = 256
is_first = true
enable_learnable_omega = true
[[net.layers]]
type = "SineLayer"
out_features = 256
enable_learnable_omega = true
[[net.layers]]
type = "SineLayer"
out_features = 256
enable_learnable_omega = true
[[net.layers]]
type = "SineLayer"
out_features = 256
enable_learnable_omega = true
[[net.layers]]
type = "Linear"
out_features = 3
need_manual_init = true
