experiment_name = "PE_MLP"

[train]
image_path = "data/kodak-dataset/kodim05.png"

num_steps = 12000
num_epochs = 1

learning_rate = 0.0001
scheduler_step_size = 1000
scheduler_gamma = 0.8

loss_type = "MSELoss"
target_loss = 0.00005
patience = 600

[save]
net_save_path = "res"
net_name = "PE_MLP"
base_output_path = "res"
image_save_path = "res"

[misc]
log_save_path = "mlruns"


[net]
num_frequencies = 10 # 位置编码的频率数量

[[net.layers]]
type = "Linear"
out_features = 256
[[net.layers]]
type = "ReLU"
out_features = 256
[[net.layers]]
type = "Linear"
out_features = 256
[[net.layers]]
type = "ReLU"
out_features = 256
[[net.layers]]
type = "Linear"
out_features = 256
[[net.layers]]
type = "ReLU"
out_features = 256
[[net.layers]]
type = "Linear"
out_features = 3 # 代码中会根据图像通道数自动处理最后一层的输出
